"""
app.py — FINRA Margin Debt Normalized Dashboard
Run: streamlit run app.py
Requires margin_data.csv generated by fetch_data.py
"""

import streamlit as st
import pandas as pd
import plotly.graph_objects as go
from pathlib import Path

# ── Page config ───────────────────────────────────────────────────────────────

st.set_page_config(
    page_title="FINRA Margin Debt — Normalized Analysis",
    page_icon="📉",
    layout="wide",
    initial_sidebar_state="collapsed",
)

# ── Theme ─────────────────────────────────────────────────────────────────────

BG     = "#0d1117"
CARD   = "#161b22"
BORDER = "#21262d"
MUTED  = "#7d8590"
DIMMED = "#484f58"
FG     = "#e6edf3"
MONO   = "'Courier New', monospace"
SANS   = "'Inter', 'Segoe UI', Arial, sans-serif"

COLORS = ["#58a6ff", "#e05c4b", "#d29922", "#3fb950"]
FILL   = ["rgba(88,166,255,0.07)", "rgba(224,92,75,0.07)",
          "rgba(210,153,34,0.07)", "rgba(63,185,80,0.07)"]

st.markdown(f"""
<style>
html, body, [class*="css"], .stApp {{
    background-color: {BG} !important;
    color: {FG};
    font-family: 'Georgia', serif;
}}
.eyebrow {{
    font-family: {MONO}; font-size: 10px; letter-spacing: .18em;
    color: {MUTED}; text-transform: uppercase; margin-bottom: 6px;
}}
.subtitle {{
    font-family: {MONO}; font-size: 11px; color: {MUTED};
}}
.panel-label {{
    font-family: {SANS}; font-size: 10px; letter-spacing: .10em;
    color: {MUTED}; text-transform: uppercase; margin-bottom: 2px;
}}
.panel-stat {{
    font-family: {SANS}; font-size: 12px; color: {MUTED}; margin-bottom: 6px;
}}
.sbox {{
    background: {CARD}; padding: 14px 16px;
    border: 1px solid {BORDER}; border-radius: 2px; height: 100%;
}}
.slabel {{
    font-family: {SANS}; font-size: 11px; letter-spacing: .10em;
    color: #ffffff; text-transform: uppercase; margin-bottom: 5px;
}}
.sval {{ font-family: {SANS}; font-size: 18px; letter-spacing: -.02em; margin-bottom: 4px; }}
.ssub {{ font-family: {SANS}; font-size: 11px; color: #ffffff; line-height: 1.6; }}
.source {{
    font-family: {SANS}; font-size: 11px; color: #ffffff;
    text-align: right; margin-top: 8px;
}}
div[data-testid="stHorizontalBlock"] {{ gap: 2px !important; }}
</style>
""", unsafe_allow_html=True)

# ── Events for vertical annotations ──────────────────────────────────────────

EVENTS = [
    ("2000-03", "Dot-com peak"),
    ("2007-07", "GFC peak"),
    ("2009-03", "GFC trough"),
    ("2020-03", "COVID"),
    ("2021-10", "2021 peak"),
]

# ── Data ──────────────────────────────────────────────────────────────────────

@st.cache_data(ttl=3600, show_spinner="Loading margin data…")
def load_data() -> pd.DataFrame:
    p = Path(__file__).parent / "margin_data.csv"
    if not p.exists():
        raise FileNotFoundError(str(p))
    df = pd.read_csv(p, index_col=0, parse_dates=True)
    df.index = pd.to_datetime(df.index)
    return df


try:
    df = load_data()
except FileNotFoundError:
    st.error("**margin_data.csv not found.** Run `python fetch_data.py` first to generate the dataset.")
    st.stop()

# ── Header ────────────────────────────────────────────────────────────────────

st.markdown(
    f'<div class="eyebrow">FINRA Rule 4521(d) · Debit Balances Normalized · '
    f'{df.index[0]:%b %Y} – {df.index[-1]:%b %Y}</div>',
    unsafe_allow_html=True,
)
st.markdown("## Margin Debt — Normalized Analysis")
st.markdown(
    '<div class="subtitle">'
    "Debit/GDP uses BEA nominal GDP (quarterly SAAR, forward-filled monthly) · "
    "Debit/Mkt Cap uses FRED BOGZ1FL073164003Q · "
    "Net Leverage = Debit ÷ Total Free Credit Balances"
    "</div>",
    unsafe_allow_html=True,
)
st.markdown("<br>", unsafe_allow_html=True)

# ── Range selector ────────────────────────────────────────────────────────────

range_col, _ = st.columns([2, 8])
with range_col:
    range_opt = st.radio(
        "Range", ["5Y", "10Y", "20Y", "All"],
        index=3, horizontal=True, label_visibility="collapsed",
    )

RANGE_MAP = {"5Y": 5, "10Y": 10, "20Y": 20, "All": None}
years = RANGE_MAP[range_opt]

dff = (
    df[df.index >= pd.Timestamp.now() - pd.DateOffset(years=years)]
    if years else df
)

# ── Chart builder ─────────────────────────────────────────────────────────────

def make_chart(
    series: pd.Series,
    color: str,
    fill_color: str,
    y_prefix: str = "",
    y_suffix: str = "",
    y_fmt: str = ".2f",
    filled: bool = False,
) -> go.Figure:
    fig = go.Figure()

    # Event vertical lines
    for date_str, label in EVENTS:
        dt = pd.Timestamp(date_str)
        if dff.index[0] <= dt <= dff.index[-1]:
            fig.add_vline(
                x=dt,
                line_color="rgba(255,255,255,0.06)",
                line_width=1,
                line_dash="dot",
                annotation=dict(
                    text=label,
                    font=dict(size=10, color="rgba(255,255,255,0.45)", family=SANS),
                    bgcolor="rgba(0,0,0,0)",
                    borderwidth=0,
                    yref="paper", y=1.0,
                    yanchor="top",
                    xanchor="left",
                    showarrow=False,
                ),
            )

    s = series.dropna()
    fig.add_trace(go.Scatter(
        x=s.index,
        y=s.values,
        mode="lines",
        line=dict(color=color, width=2),
        fill="tozeroy" if filled else "none",
        fillcolor=fill_color if filled else None,
        connectgaps=True,
        hovertemplate=(
            f"<b>%{{x|%b %Y}}</b><br>"
            f"{y_prefix}%{{y:{y_fmt}}}{y_suffix}<extra></extra>"
        ),
    ))

    tick_fmt = f"{y_fmt}" if not y_prefix and not y_suffix else y_fmt

    fig.update_layout(
        paper_bgcolor=BG,
        plot_bgcolor=CARD,
        height=220,
        margin=dict(t=4, b=4, l=4, r=52),
        showlegend=False,
        hovermode="x unified",
        font=dict(color=FG, family=SANS),
        xaxis=dict(
            showgrid=False,
            tickfont=dict(size=11, color="#ffffff", family=SANS),
            tickformat="%Y" if (years is None or years >= 10) else "%b %y",
            dtick="M12" if (years is None or years >= 5) else "M3",
            linecolor=BORDER,
        ),
        yaxis=dict(
            side="right",
            showgrid=True,
            gridcolor=BORDER,
            tickfont=dict(size=11, color="#ffffff", family=SANS),
            tickformat=tick_fmt,
            tickprefix=y_prefix,
            ticksuffix=y_suffix,
            linecolor=BORDER,
        ),
    )
    return fig


# ── Panels ────────────────────────────────────────────────────────────────────

latest = dff.dropna(subset=["debt_gdp_pct"]).iloc[-1]
latest_date = dff.index[-1].strftime("%b-%y")

panels = [
    dict(
        label="Panel 1 · Nominal (reference)",
        title="Margin Debt — Absolute ($M)",
        stat=f"{latest_date}: <span style='color:{COLORS[0]}'>${latest['debit']:,.0f}M</span>",
        series=dff["debit"],
        color=COLORS[0], fill=FILL[0],
        y_prefix="$", y_suffix="", y_fmt=",.0f", filled=False,
    ),
    dict(
        label="Panel 2 · Macro normalization",
        title="Margin Debt / Nominal GDP (%)",
        stat=f"{latest_date}: <span style='color:{COLORS[1]}'>{latest['debt_gdp_pct']:.2f}%</span>",
        series=dff["debt_gdp_pct"],
        color=COLORS[1], fill=FILL[1],
        y_prefix="", y_suffix="%", y_fmt=".2f", filled=False,
    ),
    dict(
        label="Panel 3 · Market normalization",
        title="Margin Debt / Wilshire 5000 (%)",
        stat=f"{latest_date}: <span style='color:{COLORS[2]}'>{latest['debt_mktcap_pct']:.2f}%</span>",
        series=dff["debt_mktcap_pct"],
        color=COLORS[2], fill=FILL[2],
        y_prefix="", y_suffix="%", y_fmt=".2f", filled=False,
    ),
    dict(
        label="Panel 4 · Net leverage",
        title="Debit ÷ Total Free Credit (ratio)",
        stat=f"{latest_date}: <span style='color:{COLORS[3]}'>{latest['net_leverage']:.2f}×</span>",
        series=dff["net_leverage"],
        color=COLORS[3], fill=FILL[3],
        y_prefix="", y_suffix="×", y_fmt=".2f", filled=True,
    ),
]

col_l, col_r = st.columns(2, gap="small")
for i, p in enumerate(panels):
    col = col_l if i % 2 == 0 else col_r
    with col:
        st.markdown(f'<div class="panel-label">{p["label"]}</div>', unsafe_allow_html=True)
        st.markdown(f"**{p['title']}**")
        st.markdown(f'<div class="panel-stat">{p["stat"]}</div>', unsafe_allow_html=True)
        st.plotly_chart(
            make_chart(
                p["series"], p["color"], p["fill"],
                p["y_prefix"], p["y_suffix"], p["y_fmt"], p["filled"],
            ),
            use_container_width=True,
            config={"displayModeBar": False},
        )

# ── Summary boxes ─────────────────────────────────────────────────────────────

st.markdown("<br>", unsafe_allow_html=True)
s1, s2, s3 = st.columns(3, gap="small")

gdp_v  = latest["debt_gdp_pct"]
mc_v   = latest["debt_mktcap_pct"]
lev_v  = latest["net_leverage"]

# Historical peaks (hardcoded reference points)
GDP_DOTCOM_PEAK = 2.87
MKT_GFC_PEAK    = 3.02
LEV_2021_PEAK   = 2.30

def reading_color(val, warn, danger):
    if val >= danger: return "#e05c4b"
    if val >= warn:   return "#d29922"
    return "#3fb950"

with s1:
    c = reading_color(gdp_v, GDP_DOTCOM_PEAK * 1.1, GDP_DOTCOM_PEAK * 1.25)
    label = "⚠ Elevated" if gdp_v > GDP_DOTCOM_PEAK * 1.25 else "↗ Rising" if gdp_v > GDP_DOTCOM_PEAK else "✓ Normal"
    st.markdown(f"""
    <div class="sbox">
        <div class="slabel">Debt/GDP · Reading</div>
        <div class="sval" style="color:{c}">{label}</div>
        <div class="ssub">
            {gdp_v:.2f}% vs. dot-com peak {GDP_DOTCOM_PEAK}%<br>
            GDP growth not keeping pace with margin debt<br>
            Structurally highest in 30Y series
        </div>
    </div>""", unsafe_allow_html=True)

with s2:
    c = reading_color(mc_v, MKT_GFC_PEAK * 0.65, MKT_GFC_PEAK * 0.85)
    label = "⚠ Elevated" if mc_v > MKT_GFC_PEAK * 0.85 else "↗ Rising" if mc_v > MKT_GFC_PEAK * 0.65 else "✓ Normal"
    st.markdown(f"""
    <div class="sbox">
        <div class="slabel">Debt/Mkt Cap · Reading</div>
        <div class="sval" style="color:{c}">{label}</div>
        <div class="ssub">
            {mc_v:.2f}% — elevated but below GFC ({MKT_GFC_PEAK}%)<br>
            Market cap grown faster than debt pre-2024<br>
            Ratio re-accelerating since mid-2024
        </div>
    </div>""", unsafe_allow_html=True)

with s3:
    c = reading_color(lev_v, LEV_2021_PEAK * 1.1, LEV_2021_PEAK * 1.35)
    label = "⚠ All-time high" if lev_v > LEV_2021_PEAK * 1.35 else "↗ Rising" if lev_v > LEV_2021_PEAK else "✓ Normal"
    st.markdown(f"""
    <div class="sbox">
        <div class="slabel">Net Leverage · Reading</div>
        <div class="sval" style="color:{c}">{label}</div>
        <div class="ssub">
            {lev_v:.2f}× debit vs. free credit<br>
            2021 leverage peak: {LEV_2021_PEAK}×<br>
            Acute margin-call amplification risk
        </div>
    </div>""", unsafe_allow_html=True)

# ── Source ────────────────────────────────────────────────────────────────────

st.markdown(
    '<div class="source">'
    "GDP: BEA/FRED (GDP — quarterly SAAR, forward-filled monthly) · "
    "Mkt Cap: FRED BOGZ1FL073164003Q (quarterly, forward-filled) · "
    "FINRA Rule 4521(d) margin statistics"
    "</div>",
    unsafe_allow_html=True,
)
