/**
 * LiquidityDashboard.jsx
 * Route: /liquidity
 * Place at: GitRepo\dashboards\src\pages\LiquidityDashboard.jsx
 *
 * Data source: liquidity_data.json (generated by liquidity_data.py)
 * Place JSON at: GitRepo\dashboards\public\data\liquidity_data.json
 */

import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import {
  LineChart,
  Line,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  ReferenceLine,
} from "recharts";

// ─── Design tokens ────────────────────────────────────────────────────────────
const C = {
  bg:       "#0A0E14",   // near-black with slight blue tint — terminal feel
  panel:    "#111720",   // card background
  border:   "#1C2A3A",   // subtle border
  text:     "#C9D6E3",   // cool grey — not pure white
  muted:    "#4A6070",   // labels, secondary
  accent:   "#00C2FF",   // electric cyan — the signature colour
  warn:     "#FF6B35",   // alert / negative
  pos:      "#2ECC8F",   // positive / up
  grid:     "#151E28",   // chart gridlines
};

const SERIES = [
  {
    key: "reserves",
    label: "Fed Reserve Balances",
    unit: "$B",
    color: C.accent,
    desc: "Bank reserves held at the Fed (WRESBAL). Tracks system-wide dollar liquidity.",
    source: "Bloomberg / FRED WRESBAL",
    methodology: {
      what: "Aggregate reserve balances that depository institutions hold at Federal Reserve Banks. Published weekly in the H.4.1 statistical release every Thursday at 4:30 PM ET.",
      why: "Reserves are the primary quantity signal for dollar system liquidity. When reserves are abundant, money market rates stay anchored near IORB. As reserves fall toward 'ample' or below, rate volatility increases non-linearly — small shocks produce outsized moves in funding costs. The Fed's December 2025 balance-sheet trilemma paper formalises this: sensitivity of repo rates to TGA swings rises sharply as reserves fall relative to outstanding Treasuries.",
      howToRead: "Watch the level ($3.0–3.5T currently = ample range). Direction matters more than level: a sustained decline of $200B+ over 4–6 weeks alongside rising SOFR−IORB is the key stress signal. The Fed began Reserve Management Purchases (RMPs) at $40B/month in December 2025 specifically to arrest this decline.",
      formula: "H.4.1 Table 1: 'Reserve Balances with Federal Reserve Banks'",
      links: [
        { label: "FRED WRESBAL", url: "https://fred.stlouisfed.org/series/WRESBAL" },
        { label: "H.4.1 Release (Fed)", url: "https://www.federalreserve.gov/releases/h41/" },
        { label: "Fed Balance Sheet Trilemma (Jan 2026)", url: "https://www.federalreserve.gov/econres/notes/feds-notes/the-central-bank-balance-sheet-trilemma-20260114.html" },
        { label: "NY Fed: Reserve Management Purchases", url: "https://www.newyorkfed.org/newsevents/speeches/2026/per260326" },
      ],
    },
  },
  {
    key: "onrrp",
    label: "ON RRP Usage",
    unit: "$B",
    color: C.pos,
    desc: "Overnight Reverse Repo. Near-zero means idle cash has left the Fed and re-entered markets.",
    source: "Bloomberg / FRED RRPONTSYD",
    methodology: {
      what: "Daily outstanding balance of the Fed's Overnight Reverse Repo facility. The Fed temporarily sells Treasury securities to eligible counterparties (MMFs, GSEs, primary dealers) and buys them back the next day, absorbing excess cash overnight at the ON RRP rate.",
      why: "ON RRP was the key liquidity buffer during 2022–2024 QT. It peaked at $2.55T in December 2022 and has since drained to near-zero. Crucially, while ON RRP was elevated, TGA rebuilds drained ON RRP first rather than bank reserves — acting as a shock absorber. With ON RRP now exhausted, that buffer is gone: future TGA swings now directly hit reserve balances, amplifying market impact. This is the single most important structural change in US liquidity mechanics since 2023.",
      howToRead: "Near zero = no buffer remaining. Any future TGA rebuild or reserve drain hits bank reserves directly. A sudden spike upward would signal MMFs pulling cash back to the Fed — a defensive risk-off move worth monitoring.",
      formula: "NY Fed daily: 'Temporary Open Market Operations — Overnight Reverse Repurchase Agreements'",
      links: [
        { label: "FRED RRPONTSYD", url: "https://fred.stlouisfed.org/series/RRPONTSYD" },
        { label: "NY Fed OMO Data", url: "https://www.newyorkfed.org/markets/desk-operations/repo-reverse-repo-agreements" },
        { label: "NY Fed Speech: Money Market Conditions (Nov 2025)", url: "https://www.newyorkfed.org/newsevents/speeches/2025/per251112" },
      ],
    },
  },
  {
    key: "tga",
    label: "Treasury General Account",
    unit: "$B",
    color: "#FFB347",
    desc: "TGA drawdowns inject reserves; rebuilds drain them. Mechanical liquidity swings.",
    source: "Bloomberg / FRED WTREGEN",
    methodology: {
      what: "The US Treasury's operating account at the Federal Reserve — effectively the government's checking account. Published daily in the H.4.1 release. The Treasury manages the TGA to hold approximately one week of forward cash needs (minimum ~$150B floor).",
      why: "TGA is the most mechanical driver of short-term reserve fluctuations. Every dollar the Treasury deposits into the TGA is a dollar drained from bank reserves; every dollar spent out of the TGA is injected back. With ON RRP now near-zero, TGA swings have become the dominant force in day-to-day reserve supply. Treasury has raised its assumed quarter-end TGA target from $320B (2016) to $850B on average (2025), structurally increasing the baseline drain on reserves.",
      howToRead: "Direction is everything. TGA drawdowns (falling) = liquidity injection = bullish for risk assets. TGA rebuilds (rising) = reserve drain = tightening. April tax season typically sees $175–400B of TGA inflows — watch for simultaneous repo rate spikes. The 2025 debt-limit episode saw a $420B TGA drawdown in H1, then a full rebuild post-July — reserves fell $350B in two months.",
      formula: "H.4.1 Table 1: 'U.S. Treasury, General Account' | Also: FRED WTREGEN (weekly avg)",
      links: [
        { label: "FRED WTREGEN", url: "https://fred.stlouisfed.org/series/WTREGEN" },
        { label: "Treasury Cash Management Policy", url: "https://home.treasury.gov/policy-issues/financial-markets-financial-institutions-and-fiscal-service/tbac/tbac-meeting-materials" },
        { label: "FOMC Minutes Jun 2025 (TGA/debt limit)", url: "https://www.federalreserve.gov/monetarypolicy/fomcminutes20250618.htm" },
      ],
    },
  },
  {
    key: "sofr_iorb",
    label: "SOFR − IORB Spread",
    unit: "bps",
    color: C.warn,
    desc: "Price signal for interbank dollar scarcity. Widening = tighter money market conditions.",
    source: "Bloomberg SOFRRATE / IORB Index",
    methodology: {
      what: "The spread between SOFR (Secured Overnight Financing Rate — the broad measure of overnight Treasury repo borrowing costs) and IORB (Interest on Reserve Balances — the rate the Fed pays banks on reserves). Computed daily: SOFR minus IORB, expressed in basis points.",
      why: "This is the price signal for dollar scarcity in the interbank system, complementing the quantity signals (reserves, ON RRP, TGA). When SOFR trades near or below IORB, reserves are abundant and banks are indifferent between lending in repo vs. parking at the Fed. When SOFR consistently exceeds IORB, it signals banks are reluctant to lend funds — either because reserves are scarce or balance sheet constraints are binding. The spread widened persistently above IORB from late August 2025 as TGA rebuilt and reserves fell, with the EFFR rising 4bps relative to IORB over two months.",
      howToRead: "0–5 bps = normal, abundant reserves. 5–15 bps = ample but tightening. >15 bps sustained = stress — watch for quarter-end spikes and tax-season pressure. A sustained widening alongside declining reserves is the dual confirmation that liquidity is genuinely tightening, not just seasonal noise. Also monitor the MOVE Index alongside this spread: simultaneous widening = funding stress, not just rate vol.",
      formula: "SOFR (NY Fed daily) − IORB (Fed policy rate) × 100 = spread in bps",
      links: [
        { label: "NY Fed SOFR Data", url: "https://www.newyorkfed.org/markets/reference-rates/sofr" },
        { label: "Fed IORB Rate", url: "https://www.federalreserve.gov/monetarypolicy/reserve-maintenance-manual-interest-on-reserve-balances.htm" },
        { label: "FRED SOFR", url: "https://fred.stlouisfed.org/series/SOFR" },
        { label: "FRED IORB", url: "https://fred.stlouisfed.org/series/IORB" },
        { label: "Fed Trilemma: Rate Sensitivity Analysis", url: "https://www.federalreserve.gov/econres/notes/feds-notes/the-central-bank-balance-sheet-trilemma-20260114.html" },
      ],
    },
  },
  {
    key: "bank_credit",
    label: "Bank Credit (YoY %)",
    unit: "%",
    color: "#B48EFF",
    desc: "H.8 total loans & leases growth. Expanding credit = money being put to work.",
    source: "Bloomberg / FRED H8",
    methodology: {
      what: "Year-over-year percentage change in total loans and leases at all commercial banks, from the Fed's H.8 weekly release. Covers C&I loans, real estate, consumer credit, and securities portfolios across all domestically chartered commercial banks.",
      why: "Bank credit is the velocity dimension of liquidity — it measures whether reserves are being put to work or sitting idle. A bank can hold abundant reserves and still contract credit if capital constraints, risk appetite, or regulatory requirements are binding (e.g., SLR). Expanding credit growth alongside rising reserves = genuine easing. Contracting credit despite ample reserves = impaired transmission — the system has liquidity but isn't circulating it. This is why the SLR reform debate matters: even with $3T+ in reserves, if G-SIBs face binding leverage constraints, credit intermediation can slow.",
      howToRead: "Positive and accelerating = money circulating, financial conditions easing. Negative or decelerating from positive = credit contraction, tightening regardless of reserve levels. Cross-reference with SOFR−IORB: if spread is wide AND credit growth is slowing, that is the dual confirmation of genuine tightening reaching the real economy.",
      formula: "(Current H.8 total loans & leases) / (Same week prior year) − 1, as %",
      links: [
        { label: "FRED H.8 Total Loans (TOTLL)", url: "https://fred.stlouisfed.org/series/TOTLL" },
        { label: "Fed H.8 Release", url: "https://www.federalreserve.gov/releases/h8/" },
        { label: "SLR Reform & Credit Intermediation (BPI)", url: "https://bpi.com/empty-promises-revisiting-the-reasons-to-fix-the-supplementary-leverage-ratio/" },
      ],
    },
  },
  {
    key: "dealer_net",
    label: "Dealer Treasury Positions",
    unit: "$B",
    color: "#64B5F6",
    desc: "Primary dealer net Treasury holdings. Proxy for G-SIB willingness to intermediate.",
    source: "Bloomberg NYPDDTNP Index",
    methodology: {
      what: "Net Treasury securities positions held by primary dealers, published weekly by the NY Fed (Wednesday close). Covers outright positions in Bills, Notes, Bonds, TIPS, and FRNs across the 24 primary dealers who are required to bid at Treasury auctions and act as market makers.",
      why: "This is the quantity signal for G-SIB intermediation capacity — the missing link between reserve levels and actual market liquidity. Reserves measure what's available at the Fed; dealer positions measure how much of that capacity is being deployed into Treasury markets. When dealers shrink net long positions, they're either facing SLR constraints, risk-off, or pulling back ahead of balance sheet reporting dates (quarter-ends). A declining dealer position alongside widening SOFR−IORB is the dual confirmation of stress in Treasury market intermediation — the exact mechanism behind the Sept 2019 repo crisis and the April 2020 'dash for cash'.",
      howToRead: "Rising net positions = dealers absorbing supply, intermediation healthy. Falling net positions = dealers pulling back — watch for widening bid-ask spreads in Treasuries and repo rate spikes. Quarter-end drops are seasonal; sustained multi-week declines are structural. Cross-reference with MOVE Index for rate volatility context.",
      formula: "NY Fed Primary Dealer Statistics: net position in all Treasury coupons + bills + TIPS",
      links: [
        { label: "NY Fed Primary Dealer Statistics", url: "https://www.newyorkfed.org/markets/counterparties/primary-dealers-statistics" },
        { label: "Fed Note: Dealers & SLR", url: "https://www.federalreserve.gov/econres/notes/feds-notes/dealers-treasury-market-intermediation-and-the-supplementary-leverage-ratio-20230803.html" },
        { label: "SLR Reform Proposal (Federal Register Dec 2025)", url: "https://www.federalregister.gov/documents/2025/12/01/2025-21626/regulatory-capital-rule-modifications-to-the-enhanced-supplementary-leverage-ratio-standards-for-us" },
        { label: "BNY: Leverage Ratio Reform & Treasury Liquidity", url: "https://www.bny.com/corporate/global/en/insights/us-treasury-liquidity-leverage-reform.html" },
      ],
    },
  },
  {
    key: "move",
    label: "MOVE Index",
    unit: "pts",
    color: "#FF8A65",
    desc: "Treasury rate volatility index. Overlay signal for repo market stress.",
    source: "Bloomberg MOVE Index",
    methodology: {
      what: "The ICE BofA MOVE Index measures implied volatility in the US Treasury market, derived from 1-month options on 2Y, 5Y, 10Y, and 30Y Treasuries (weighted). It is the fixed income equivalent of the VIX — a forward-looking measure of expected rate volatility over the next month.",
      why: "MOVE is the contextual overlay for interpreting SOFR−IORB spread movements. When SOFR−IORB widens alongside elevated MOVE, it indicates genuine funding stress — dealers and money market participants are demanding higher compensation to lend because rate uncertainty is high. When SOFR−IORB widens but MOVE is low, it may be a seasonal or technical effect (quarter-end, tax date) rather than systemic stress. Recent research (2026 macro outlook) explicitly pairs SOFR−IORB deviation with the MOVE Index as the two-variable framework for assessing onshore USD funding pressure.",
      howToRead: "MOVE < 80: calm, normal functioning. MOVE 80–120: elevated vol, watch spread signals. MOVE > 120: stress regime — cross-reference with all other indicators. Historical stress episodes: COVID March 2020 (~160), SVB March 2023 (~190), Sept 2019 repo crisis (~70 but with extreme SOFR spike).",
      formula: "ICE BofA MOVE Index = weighted average of normalized implied vols on 2Y/5Y/10Y/30Y Treasury options",
      links: [
        { label: "Bloomberg MOVE Index (ICE)", url: "https://www.ice.com/products/45581109/ICE-BofA-MOVE-Index" },
        { label: "FRED MOVE Proxy (VXTYN)", url: "https://fred.stlouisfed.org/series/VXTYN" },
        { label: "2026 USD Liquidity Outlook", url: "https://news.futunn.com/en/post/66915126/macroeconomic-outlook-2026-us-dollar-liquidity" },
      ],
    },
  },
];

// ─── Helpers ──────────────────────────────────────────────────────────────────
const fmt = (v, unit) => {
  if (v == null) return "—";
  if (unit === "bps") return `${v.toFixed(1)} bps`;
  if (unit === "%") return `${v.toFixed(2)}%`;
  return `$${Math.round(v).toLocaleString()}B`;
};

const delta = (arr, key) => {
  if (!arr || arr.length < 2) return null;
  const last = arr[arr.length - 1][key];
  const prev = arr[arr.length - 2][key];
  if (last == null || prev == null) return null;
  return last - prev;
};

const CustomTooltip = ({ active, payload, label, unit }) => {
  if (!active || !payload?.length) return null;
  return (
    <div style={{
      background: C.panel,
      border: `1px solid ${C.border}`,
      borderRadius: 6,
      padding: "10px 14px",
      fontFamily: "'JetBrains Mono', monospace",
      fontSize: 12,
    }}>
      <div style={{ color: C.muted, marginBottom: 4 }}>{label}</div>
      {payload.map((p) => (
        <div key={p.dataKey} style={{ color: p.color }}>
          {fmt(p.value, unit)}
        </div>
      ))}
    </div>
  );
};

// ─── Methodology drawer ───────────────────────────────────────────────────────
const MethodologyDrawer = ({ series, onClose }) => {
  const m = series.methodology;
  if (!m) return null;

  const section = (label, content) => (
    <div style={{ marginBottom: 18 }}>
      <div style={{
        fontSize: 9, letterSpacing: "0.12em", textTransform: "uppercase",
        color: series.color, fontFamily: "monospace", marginBottom: 6,
      }}>
        {label}
      </div>
      <div style={{ fontSize: 12.5, color: C.text, lineHeight: 1.7 }}>{content}</div>
    </div>
  );

  return (
    <div style={{
      position: "fixed", inset: 0, zIndex: 100,
      display: "flex", alignItems: "flex-end", justifyContent: "flex-end",
    }}>
      {/* Backdrop */}
      <div
        onClick={onClose}
        style={{ position: "absolute", inset: 0, background: "rgba(0,0,0,0.55)" }}
      />
      {/* Panel */}
      <div style={{
        position: "relative", zIndex: 1,
        width: "min(560px, 95vw)", height: "100vh",
        background: C.panel,
        borderLeft: `1px solid ${series.color}50`,
        overflowY: "auto",
        padding: "28px 28px 48px",
      }}>
        {/* Header */}
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 24 }}>
          <div>
            <div style={{
              fontSize: 9, letterSpacing: "0.12em", textTransform: "uppercase",
              color: series.color, fontFamily: "monospace", marginBottom: 6,
            }}>
              Indicator Methodology
            </div>
            <div style={{ fontSize: 18, fontWeight: 600, color: C.text }}>{series.label}</div>
          </div>
          <button
            onClick={onClose}
            style={{
              background: "none", border: `1px solid ${C.border}`, borderRadius: 6,
              color: C.muted, fontSize: 13, padding: "4px 10px", cursor: "pointer",
            }}
          >
            ✕
          </button>
        </div>

        <div style={{ width: 40, height: 2, background: series.color, marginBottom: 24, borderRadius: 2 }} />

        {section("What it is", m.what)}
        {section("Why it matters", m.why)}
        {section("How to read it", m.howToRead)}
        {m.formula && section("Construction / formula", (
          <code style={{
            display: "block", background: C.bg, borderRadius: 6,
            padding: "10px 14px", fontSize: 11.5, color: C.accent,
            fontFamily: "monospace", lineHeight: 1.6, whiteSpace: "pre-wrap",
          }}>
            {m.formula}
          </code>
        ))}

        {/* Links */}
        <div style={{ marginTop: 24 }}>
          <div style={{
            fontSize: 9, letterSpacing: "0.12em", textTransform: "uppercase",
            color: series.color, fontFamily: "monospace", marginBottom: 12,
          }}>
            Primary Sources
          </div>
          <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
            {m.links.map((link) => (
              <a
                key={link.url}
                href={link.url}
                target="_blank"
                rel="noopener noreferrer"
                style={{
                  display: "flex", alignItems: "center", gap: 10,
                  padding: "10px 14px",
                  background: C.bg,
                  border: `1px solid ${C.border}`,
                  borderRadius: 6,
                  color: C.text,
                  fontSize: 12,
                  textDecoration: "none",
                  transition: "border-color 0.15s",
                }}
                onMouseEnter={(e) => e.currentTarget.style.borderColor = series.color}
                onMouseLeave={(e) => e.currentTarget.style.borderColor = C.border}
              >
                <span style={{
                  width: 6, height: 6, borderRadius: "50%",
                  background: series.color, flexShrink: 0,
                }} />
                {link.label}
                <span style={{ marginLeft: "auto", color: C.muted, fontSize: 10 }}>↗</span>
              </a>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
};

// ─── Stat card ────────────────────────────────────────────────────────────────
const StatCard = ({ series, data, onClick, active }) => {
  const last = data?.[data.length - 1]?.[series.key];
  const d = delta(data, series.key);
  const isPos = d !== null && d >= 0;
  const border = active ? series.color : C.border;

  return (
    <button
      onClick={onClick}
      style={{
        background: C.panel,
        border: `1px solid ${border}`,
        borderRadius: 8,
        padding: "16px 20px",
        cursor: "pointer",
        textAlign: "left",
        width: "100%",
        transition: "border-color 0.15s",
        outline: "none",
      }}
    >
      <div style={{ fontSize: 10, color: C.muted, letterSpacing: "0.1em", textTransform: "uppercase", marginBottom: 6 }}>
        {series.label}
      </div>
      <div style={{ fontSize: 22, fontWeight: 700, color: series.color, fontFamily: "'JetBrains Mono', monospace" }}>
        {fmt(last, series.unit)}
      </div>
      {d !== null && (
        <div style={{ fontSize: 11, color: isPos ? C.pos : C.warn, marginTop: 4 }}>
          {isPos ? "▲" : "▼"} {fmt(Math.abs(d), series.unit)} vs prior
        </div>
      )}
    </button>
  );
};

// ─── Chart panel ─────────────────────────────────────────────────────────────
const ChartPanel = ({ series, data, onMethodology }) => {
  const zeroLine = series.key === "sofr_iorb";

  return (
    <div style={{
      background: C.panel,
      border: `1px solid ${series.color}40`,
      borderRadius: 10,
      padding: "24px 20px 16px",
    }}>
      {/* Header */}
      <div style={{ marginBottom: 20 }}>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start" }}>
          <div>
            <span style={{
              fontSize: 10, color: series.color, letterSpacing: "0.1em",
              textTransform: "uppercase", fontFamily: "'JetBrains Mono', monospace",
            }}>
              {series.label}
            </span>
            <p style={{ fontSize: 12, color: C.muted, margin: "6px 0 0", maxWidth: 560 }}>
              {series.desc}
            </p>
          </div>
          <div style={{ display: "flex", alignItems: "center", gap: 10, paddingLeft: 16, flexShrink: 0 }}>
            <span style={{
              fontSize: 10, color: C.muted, fontFamily: "'JetBrains Mono', monospace",
              whiteSpace: "nowrap",
            }}>
              {series.source}
            </span>
            {series.methodology && onMethodology && (
              <button
                onClick={(e) => { e.stopPropagation(); onMethodology(series); }}
                title="View methodology & sources"
                style={{
                  background: "none",
                  border: `1px solid ${series.color}60`,
                  borderRadius: "50%",
                  width: 20, height: 20,
                  color: series.color,
                  fontSize: 11, fontWeight: 700,
                  cursor: "pointer",
                  display: "flex", alignItems: "center", justifyContent: "center",
                  flexShrink: 0,
                  lineHeight: 1,
                }}
              >
                ?
              </button>
            )}
          </div>
        </div>
      </div>

      {/* Chart */}
      {data && data.length > 0 ? (
        <ResponsiveContainer width="100%" height={220}>
          <LineChart data={data} margin={{ top: 4, right: 8, left: 0, bottom: 0 }}>
            <CartesianGrid stroke={C.grid} strokeDasharray="3 3" />
            <XAxis
              dataKey="date"
              tick={{ fill: C.muted, fontSize: 10, fontFamily: "monospace" }}
              tickLine={false}
              axisLine={{ stroke: C.border }}
              interval="preserveStartEnd"
            />
            <YAxis
              tick={{ fill: C.muted, fontSize: 10, fontFamily: "monospace" }}
              tickLine={false}
              axisLine={false}
              tickFormatter={(v) =>
                series.unit === "bps" ? `${v}` :
                series.unit === "%" ? `${v}%` :
                `${Math.round(v / 1000)}T`
              }
              width={42}
            />
            <Tooltip content={<CustomTooltip unit={series.unit} />} />
            {zeroLine && (
              <ReferenceLine y={0} stroke={C.muted} strokeDasharray="4 4" />
            )}
            <Line
              type="monotone"
              dataKey={series.key}
              stroke={series.color}
              strokeWidth={1.8}
              dot={false}
              activeDot={{ r: 4, fill: series.color }}
              connectNulls
            />
          </LineChart>
        </ResponsiveContainer>
      ) : (
        <div style={{
          height: 220, display: "flex", alignItems: "center", justifyContent: "center",
          color: C.muted, fontSize: 13, fontFamily: "monospace",
        }}>
          No data — run liquidity_data.py to populate public/data/liquidity_data.json
        </div>
      )}
    </div>
  );
};

// ─── Main ─────────────────────────────────────────────────────────────────────
export default function LiquidityDashboard() {
  const navigate = useNavigate();
  const [data, setData] = useState(null);
  const [activeSeries, setActiveSeries] = useState(SERIES[0].key);
  const [lastUpdated, setLastUpdated] = useState(null);
  const [error, setError] = useState(null);
  const [methodologySeries, setMethodologySeries] = useState(null);

  useEffect(() => {
    fetch(`${import.meta.env.BASE_URL}data/liquidity_data.json`)
      .then((r) => {
        if (!r.ok) throw new Error("Data file not found");
        return r.json();
      })
      .then((json) => {
        setData(json.series);
        setLastUpdated(json.updated_at);
      })
      .catch((e) => {
        setError(e.message);
        // Load demo data so layout is visible
        setData(generateDemoData());
      });
  }, []);

  const activeDef = SERIES.find((s) => s.key === activeSeries);

  return (
    <div style={{
      minHeight: "100vh",
      background: C.bg,
      color: C.text,
      fontFamily: "'Inter', system-ui, sans-serif",
      padding: "0 0 60px",
    }}>
      {/* ── Top bar ── */}
      <div style={{
        borderBottom: `1px solid ${C.border}`,
        padding: "14px 32px",
        display: "flex",
        alignItems: "center",
        gap: 16,
        position: "sticky",
        top: 0,
        background: `${C.bg}EE`,
        backdropFilter: "blur(6px)",
        zIndex: 10,
      }}>
        <button
          onClick={() => navigate("/")}
          style={{
            background: "none", border: `1px solid ${C.border}`, borderRadius: 6,
            color: C.muted, fontSize: 12, padding: "4px 12px", cursor: "pointer",
          }}
        >
          ← Home
        </button>
        <div style={{ width: 1, height: 18, background: C.border }} />
        <div style={{ display: "flex", alignItems: "baseline", gap: 10 }}>
          <span style={{
            fontSize: 13, fontWeight: 600, letterSpacing: "0.06em",
            textTransform: "uppercase", color: C.accent,
            fontFamily: "'JetBrains Mono', monospace",
          }}>
            US Liquidity
          </span>
          <span style={{ fontSize: 11, color: C.muted }}>
            Fed Plumbing Dashboard
          </span>
        </div>
        <div style={{ marginLeft: "auto", display: "flex", alignItems: "center", gap: 12 }}>
          <button
            onClick={() => setMethodologySeries(SERIES.find(s => s.key === activeSeries))}
            style={{
              background: "none", border: `1px solid ${C.border}`, borderRadius: 6,
              color: C.muted, fontSize: 11, padding: "4px 12px", cursor: "pointer",
              letterSpacing: "0.04em",
            }}
          >
            Methodology ↗
          </button>
          {error && (
            <span style={{ fontSize: 11, color: C.warn }}>⚠ Demo data — run liquidity_data.py</span>
          )}
          {lastUpdated && (
            <span style={{ fontSize: 11, color: C.muted, fontFamily: "monospace" }}>
              Updated {lastUpdated}
            </span>
          )}
          <div style={{
            width: 7, height: 7, borderRadius: "50%",
            background: error ? C.warn : C.pos,
            boxShadow: `0 0 6px ${error ? C.warn : C.pos}`,
          }} />
        </div>
      </div>

      {/* ── Main content ── */}
      <div style={{ maxWidth: 1100, margin: "0 auto", padding: "32px 24px" }}>

        {/* Title block */}
        <div style={{ marginBottom: 32 }}>
          <h1 style={{
            fontSize: 28, fontWeight: 300, margin: 0, letterSpacing: "-0.02em",
            color: C.text,
          }}>
            Federal Reserve{" "}
            <span style={{ color: C.accent, fontWeight: 700 }}>Liquidity</span>
          </h1>
          <p style={{ margin: "8px 0 0", color: C.muted, fontSize: 13, maxWidth: 580 }}>
            Real-time tracking of dollar system plumbing — reserve balances, RRP, TGA,
            and interbank spread conditions. Data via Bloomberg (primary) / FRED (fallback).
          </p>
        </div>

        {/* Stat cards grid */}
        <div style={{
          display: "grid",
          gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
          gap: 12,
          marginBottom: 32,
        }}>
          {SERIES.map((s) => (
            <StatCard
              key={s.key}
              series={s}
              data={data}
              active={activeSeries === s.key}
              onClick={() => setActiveSeries(s.key)}
            />
          ))}
        </div>

        {/* Active chart — full width */}
        {activeDef && (
          <div style={{ marginBottom: 24 }}>
            <ChartPanel
              series={activeDef}
              data={data}
              onMethodology={setMethodologySeries}
            />
          </div>
        )}

        {/* Small multiples — all other series */}
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16 }}>
          {SERIES.filter((s) => s.key !== activeSeries).map((s) => (
            <div
              key={s.key}
              onClick={() => setActiveSeries(s.key)}
              style={{ cursor: "pointer" }}
            >
              <ChartPanel
                series={s}
                data={data}
                onMethodology={setMethodologySeries}
              />
            </div>
          ))}
        </div>

        {/* Methodology drawer */}
        {methodologySeries && (
          <MethodologyDrawer
            series={methodologySeries}
            onClose={() => setMethodologySeries(null)}
          />
        )}

        {/* Footer note */}
        <div style={{
          marginTop: 40, padding: "16px 0",
          borderTop: `1px solid ${C.border}`,
          fontSize: 11, color: C.muted, display: "flex", justifyContent: "space-between",
        }}>
          <span>Sources: Bloomberg WRESBAL, SOFRRATE, IORB, NYPDDTNP, MOVE — FRED RRPONTSYD, WTREGEN, TOTLL</span>
          <span>Centile Partners · Internal Use</span>
        </div>
      </div>
    </div>
  );
}

// ─── Demo data (shown when JSON not yet generated) ────────────────────────────
function generateDemoData() {
  const out = [];
  const start = new Date("2023-01-01");
  let reserves = 3100, onrrp = 2200, tga = 450, spread = 5, credit = 7;
  let dealer = 180, move = 95;
  for (let i = 0; i < 120; i++) {
    const d = new Date(start);
    d.setDate(d.getDate() + i * 3);
    reserves += (Math.random() - 0.52) * 40;
    onrrp    = Math.max(0, onrrp - (Math.random() * 60));
    tga      += (Math.random() - 0.5) * 80;
    spread   += (Math.random() - 0.5) * 2;
    credit   += (Math.random() - 0.52) * 0.3;
    dealer   += (Math.random() - 0.5) * 15;
    move     = Math.max(50, Math.min(160, move + (Math.random() - 0.5) * 8));
    out.push({
      date:        d.toISOString().slice(0, 10),
      reserves:    +reserves.toFixed(1),
      onrrp:       +onrrp.toFixed(1),
      tga:         +tga.toFixed(1),
      sofr_iorb:   +spread.toFixed(2),
      bank_credit: +credit.toFixed(2),
      dealer_net:  +dealer.toFixed(1),
      move:        +move.toFixed(1),
    });
  }
  return out;
}
